import type {
  ProductItem,
  Quotation,
  ApprovalItem,
  FulfillmentItem,
  SubscriptionItem,
  InvoiceItem,
  DealHealthItem,
  PortalChatMessage,
} from '../stores/dealflowStore';

export interface MockCategory {
  id: number;
  name: string;
  maxDiscountPct: number;
}

export interface MockCustomer {
  id: number;
  name: string;
  email: string;
  tier: 'Bronze' | 'Silver' | 'Gold';
  maxDiscountPct: number;
  paymentTerms: string;
  address?: string;
}

export const MOCK_CUSTOMERS: MockCustomer[] = [
  { id: 1, name: 'Stark Industries', email: 'procurement@stark-industries.com', tier: 'Gold', maxDiscountPct: 15, paymentTerms: 'Net 30 Days', address: '10880 Wilshire Blvd, Los Angeles, CA' },
  { id: 2, name: 'Wayne Enterprises Tech Lab', email: 'procurement@wayne-tech.com', tier: 'Gold', maxDiscountPct: 15, paymentTerms: 'Immediate Payment', address: '1007 Mountain Drive, Gotham' },
  { id: 3, name: 'Cyberdyne Systems Corp', email: 'orders@cyberdyne.io', tier: 'Silver', maxDiscountPct: 10, paymentTerms: 'Net 15 Days', address: '18144 El Camino Real, Sunnyvale, CA' },
  { id: 4, name: 'Acme Corp Procurement', email: 'procurement@acme.com', tier: 'Bronze', maxDiscountPct: 5, paymentTerms: 'Net 30 Days', address: '123 Industrial Way, Dallas, TX' },
  { id: 5, name: 'Omni Consumer Products', email: 'purchasing@ocp-corp.com', tier: 'Silver', maxDiscountPct: 10, paymentTerms: 'Net 30 Days', address: '100 Delta City Plaza, Detroit, MI' },
  { id: 6, name: 'Tyrell BioTech Labs', email: 'supply@tyrell-corp.com', tier: 'Bronze', maxDiscountPct: 5, paymentTerms: 'Net 15 Days', address: 'Sector 4 Pyramid, Los Angeles, CA' },
  { id: 7, name: 'Initech Systems Inc.', email: 'orders@initech.com', tier: 'Silver', maxDiscountPct: 10, paymentTerms: 'Net 30 Days', address: '4120 Freidrich Lane, Austin, TX' },
  { id: 8, name: 'Massive Dynamic Corp', email: 'procurement@massivedynamic.com', tier: 'Gold', maxDiscountPct: 15, paymentTerms: 'Net 60 Days', address: '650 Townsend St, New York, NY' },
];

export const MOCK_CATEGORIES: MockCategory[] = [
  { id: 1, name: 'Hardware', maxDiscountPct: 15 },
  { id: 2, name: 'Accessories', maxDiscountPct: 20 },
  { id: 3, name: 'Services', maxDiscountPct: 10 },
  { id: 4, name: 'Subscriptions', maxDiscountPct: 25 },
];

export const MOCK_PRODUCTS: ProductItem[] = [
  {
    id: 'prod-1',
    name: 'Titan Blade Server Node X8',
    sku: 'SRV-TITAN-01',
    category: 'Hardware',
    salesPrice: 245000,
    costPrice: 165000,
    status: 'Active',
    description: 'High-density enterprise compute node with dual Xeon processors and 256GB ECC RAM.',
    canBeSold: true,
    canBePurchased: true,
  },
  {
    id: 'prod-2',
    name: 'Pro Laptop 16" M-Max (32GB/1TB)',
    sku: 'LPT-PRO-16',
    category: 'Hardware',
    salesPrice: 185000,
    costPrice: 142000,
    status: 'Active',
    description: 'Executive workstation with liquid retina display and all-day battery life.',
    canBeSold: true,
    canBePurchased: true,
  },
  {
    id: 'prod-3',
    name: 'Wireless Ergonomic Keyboard & Mouse Suite',
    sku: 'ACC-KB-990',
    category: 'Accessories',
    salesPrice: 7500,
    costPrice: 4200,
    status: 'Active',
    description: 'Multi-device Bluetooth mechanical desktop bundle with wrist rest.',
    canBeSold: true,
    canBePurchased: true,
  },
  {
    id: 'prod-4',
    name: 'Enterprise Fiber Switch 48-Port 10GbE',
    sku: 'NET-SW-48F',
    category: 'Hardware',
    salesPrice: 115000,
    costPrice: 78000,
    status: 'Active',
    description: 'L3 managed rack-mount fiber optic switch with redundant power supplies.',
    canBeSold: true,
    canBePurchased: true,
  },
  {
    id: 'prod-5',
    name: '24/7 Dedicated SLA Infrastructure Support',
    sku: 'SRV-SLA-247',
    category: 'Services',
    salesPrice: 45000,
    costPrice: 18000,
    status: 'Active',
    description: 'Priority incident response within 15 minutes and dedicated technical account manager.',
    canBeSold: true,
    canBePurchased: false,
  },
  {
    id: 'prod-6',
    name: 'DealFlow360 Enterprise ERP License (Monthly)',
    sku: 'SUB-ERP-ENT',
    category: 'Subscriptions',
    salesPrice: 12000,
    costPrice: 1500,
    status: 'Active',
    description: 'Cloud CPQ, quotations, billing, and automated multi-warehouse order fulfillment platform.',
    canBeSold: true,
    canBePurchased: false,
  },
  {
    id: 'prod-7',
    name: 'Custom On-Site Deployment & Migration Package',
    sku: 'SRV-DEPLOY-01',
    category: 'Services',
    salesPrice: 95000,
    costPrice: 35000,
    status: 'Active',
    description: 'Hands-on architectural setup, legacy data import, and staff training.',
    canBeSold: true,
    canBePurchased: false,
  },
  {
    id: 'prod-8',
    name: 'Thunderbolt 4 Triple-Display Docking Station',
    sku: 'ACC-TB4-DK',
    category: 'Accessories',
    salesPrice: 18500,
    costPrice: 11000,
    status: 'Active',
    description: 'Power delivery up to 100W with dual HDMI 2.1, DisplayPort, and 2.5G Ethernet.',
    canBeSold: true,
    canBePurchased: true,
  },
];

export const MOCK_QUOTATIONS: Quotation[] = [
  {
    id: 'q-1',
    reference: 'SO/2026/00142',
    customerName: 'Stark Industries',
    customerTier: 'Gold',
    date: '2026-09-04',
    expiryDate: '2026-09-30',
    paymentTerms: 'Net 30 Days',
    status: 'Pending Approval',
    lines: [
      {
        id: 'ql-1',
        productId: 'prod-1',
        productName: 'Titan Blade Server Node X8',
        category: 'Hardware',
        description: 'Primary datacenter expansion nodes',
        quantity: 4,
        unitPrice: 245000,
        discount: 18,
        allowedDiscount: 15,
        taxPercent: 18,
        total: 803600,
      },
      {
        id: 'ql-2',
        productId: 'prod-5',
        productName: '24/7 Dedicated SLA Infrastructure Support',
        category: 'Services',
        description: 'Enterprise 1-year coverage',
        quantity: 1,
        unitPrice: 45000,
        discount: 10,
        allowedDiscount: 10,
        taxPercent: 18,
        total: 40500,
      },
      {
        id: 'ql-3',
        productId: 'prod-6',
        productName: 'DealFlow360 Enterprise ERP License (Monthly)',
        category: 'Subscriptions',
        description: '25-seat monthly subscription plan',
        quantity: 25,
        unitPrice: 12000,
        discount: 5,
        allowedDiscount: 20,
        taxPercent: 18,
        total: 285000,
      },
    ],
    untaxedAmount: 1129100,
    taxAmount: 203238,
    totalAmount: 1332338,
    blendedRiskScore: 19.4,
    requiresManagerApproval: true,
    requiresFinanceApproval: true,
  },
  {
    id: 'q-2',
    reference: 'SO/2026/00141',
    customerName: 'Wayne Enterprises Tech Lab',
    customerTier: 'Gold',
    date: '2026-09-02',
    expiryDate: '2026-09-25',
    paymentTerms: 'Immediate Payment',
    status: 'Approved',
    lines: [
      {
        id: 'ql-4',
        productId: 'prod-2',
        productName: 'Pro Laptop 16" M-Max (32GB/1TB)',
        category: 'Hardware',
        description: 'Engineering fleet refresh',
        quantity: 6,
        unitPrice: 185000,
        discount: 12,
        allowedDiscount: 15,
        taxPercent: 18,
        total: 976800,
      },
      {
        id: 'ql-5',
        productId: 'prod-8',
        productName: 'Thunderbolt 4 Triple-Display Docking Station',
        category: 'Accessories',
        description: 'Desk docking stations',
        quantity: 6,
        unitPrice: 18500,
        discount: 10,
        allowedDiscount: 20,
        taxPercent: 18,
        total: 99900,
      },
    ],
    untaxedAmount: 1076700,
    taxAmount: 193806,
    totalAmount: 1270506,
    blendedRiskScore: 8.2,
    requiresManagerApproval: false,
    requiresFinanceApproval: false,
  },
  {
    id: 'q-3',
    reference: 'SO/2026/00140',
    customerName: 'Cyberdyne Systems Corp',
    customerTier: 'Silver',
    date: '2026-09-01',
    expiryDate: '2026-09-20',
    paymentTerms: 'Net 15 Days',
    status: 'Confirmed',
    lines: [
      {
        id: 'ql-6',
        productId: 'prod-4',
        productName: 'Enterprise Fiber Switch 48-Port 10GbE',
        category: 'Hardware',
        description: 'Rack level routing switches',
        quantity: 2,
        unitPrice: 115000,
        discount: 8,
        allowedDiscount: 10,
        taxPercent: 18,
        total: 211600,
      },
      {
        id: 'ql-7',
        productId: 'prod-7',
        productName: 'Custom On-Site Deployment & Migration Package',
        category: 'Services',
        description: 'Installation & switch configuration',
        quantity: 1,
        unitPrice: 95000,
        discount: 5,
        allowedDiscount: 10,
        taxPercent: 18,
        total: 90250,
      },
    ],
    untaxedAmount: 301850,
    taxAmount: 54333,
    totalAmount: 356183,
    blendedRiskScore: 6.5,
    requiresManagerApproval: false,
    requiresFinanceApproval: false,
  },
  {
    id: 'q-4',
    reference: 'SO/2026/00139',
    customerName: 'Acme Corp Procurement',
    customerTier: 'Bronze',
    date: '2026-08-28',
    expiryDate: '2026-09-15',
    paymentTerms: 'Net 30 Days',
    status: 'Draft',
    lines: [
      {
        id: 'ql-8',
        productId: 'prod-3',
        productName: 'Wireless Ergonomic Keyboard & Mouse Suite',
        category: 'Accessories',
        description: 'Office supply batch order',
        quantity: 20,
        unitPrice: 7500,
        discount: 5,
        allowedDiscount: 5,
        taxPercent: 18,
        total: 142500,
      },
    ],
    untaxedAmount: 142500,
    taxAmount: 25650,
    totalAmount: 168150,
    blendedRiskScore: 3.1,
    requiresManagerApproval: false,
    requiresFinanceApproval: false,
  },
];

export const MOCK_APPROVALS: ApprovalItem[] = [
  {
    id: 'app-1',
    reference: 'APP/2026/00028',
    quotationId: 'q-1',
    customerName: 'Stark Industries',
    requestType: 'Discount Approval',
    amount: 1332338,
    requestedBy: 'Peter Parker (Sales Rep)',
    requestedDate: '2026-09-04 14:32',
    status: 'Pending',
    blendedRiskScore: 19.4,
    reason: 'Client requested 18% discount on Blade Servers (tier limit is 15%) to close enterprise deal before quarter-end.',
    auditTrail: [
      {
        step: 'Quotation Created',
        user: 'Peter Parker',
        status: 'Draft',
        timestamp: '2026-09-04 14:10',
      },
      {
        step: 'Discount Exceeded Triggered',
        user: 'DealFlow360 Rule Engine',
        status: 'Flagged',
        timestamp: '2026-09-04 14:30',
        note: 'Blended risk score calculated at 19.4% (Threshold: 15%)',
      },
      {
        step: 'Approval Escalated to Manager',
        user: 'System',
        status: 'Pending',
        timestamp: '2026-09-04 14:32',
      },
    ],
  },
  {
    id: 'app-2',
    reference: 'APP/2026/00027',
    quotationId: 'q-2',
    customerName: 'Wayne Enterprises Tech Lab',
    requestType: 'Credit Limit Increase',
    amount: 1270506,
    requestedBy: 'Bruce Vance (Sales Rep)',
    requestedDate: '2026-09-02 11:15',
    status: 'Approved',
    blendedRiskScore: 8.2,
    reason: 'Standard tier credit extension requested for recurring volume order.',
    auditTrail: [
      {
        step: 'Submitted',
        user: 'Bruce Vance',
        status: 'Pending',
        timestamp: '2026-09-02 11:15',
      },
      {
        step: 'Manager Sign-off',
        user: 'Alex Rivera (Sales Manager)',
        status: 'Approved',
        timestamp: '2026-09-02 13:40',
        note: 'Approved based on pristine credit history and Gold Tier status.',
      },
    ],
  },
];

export const MOCK_FULFILLMENTS: FulfillmentItem[] = [
  {
    id: 'ful-1',
    reference: 'WH/OUT/00140',
    quotationReference: 'SO/2026/00140',
    customerName: 'Cyberdyne Systems Corp',
    scheduledDate: '2026-09-08',
    status: 'Ready',
    responsible: 'Marcus Wright',
    lines: [
      {
        productName: 'Enterprise Fiber Switch 48-Port 10GbE',
        description: 'Rack level routing switches',
        demand: 2,
        done: 2,
        unit: 'unit',
      },
    ],
    splits: [
      {
        warehouseName: 'Central Hub - Mumbai (WH-01)',
        quantityFulfilled: 2,
        stockAvailable: 14,
        estimatedCost: 1200,
        shipmentCount: 1,
      },
    ],
  },
  {
    id: 'ful-2',
    reference: 'WH/OUT/00138',
    quotationReference: 'SO/2026/00138',
    customerName: 'Omni Consumer Products',
    scheduledDate: '2026-09-06',
    status: 'Shipped',
    responsible: 'Sarah Connor',
    lines: [
      {
        productName: 'Pro Laptop 16" M-Max (32GB/1TB)',
        description: 'Engineering laptops',
        demand: 10,
        done: 10,
        unit: 'unit',
      },
    ],
    splits: [
      {
        warehouseName: 'Central Hub - Mumbai (WH-01)',
        quantityFulfilled: 7,
        stockAvailable: 2,
        estimatedCost: 3500,
        shipmentCount: 1,
      },
      {
        warehouseName: 'Regional Hub - Bengaluru (WH-02)',
        quantityFulfilled: 3,
        stockAvailable: 18,
        estimatedCost: 1800,
        shipmentCount: 1,
      },
    ],
  },
];

export const MOCK_SUBSCRIPTIONS: SubscriptionItem[] = [
  {
    id: 'sub-1',
    reference: 'SUB/2026/00054',
    customerName: 'Stark Industries',
    planName: 'Enterprise CPQ & DealFlow Suite',
    startDate: '2026-01-15',
    nextBillingDate: '2026-10-01',
    billingFrequency: 'Monthly',
    status: 'Active',
    recurringLines: [
      {
        productName: 'DealFlow360 Enterprise ERP License (Monthly)',
        description: 'Core Seat Licenses',
        quantity: 25,
        unitPrice: 12000,
        amount: 300000,
      },
      {
        productName: '24/7 Dedicated SLA Infrastructure Support',
        description: 'Monthly Maintenance Fee',
        quantity: 1,
        unitPrice: 45000,
        amount: 45000,
      },
    ],
  },
  {
    id: 'sub-2',
    reference: 'SUB/2026/00051',
    customerName: 'Wayne Enterprises Tech Lab',
    planName: 'Business Operations Plan',
    startDate: '2026-03-01',
    nextBillingDate: '2026-09-30',
    billingFrequency: 'Quarterly',
    status: 'Active',
    recurringLines: [
      {
        productName: 'DealFlow360 Enterprise ERP License (Monthly)',
        description: 'Quarterly Advance Billing (10 seats)',
        quantity: 10,
        unitPrice: 36000,
        amount: 360000,
      },
    ],
  },
];

export const MOCK_INVOICES: InvoiceItem[] = [
  {
    id: 'inv-1',
    reference: 'INV/2026/00219',
    customerName: 'Cyberdyne Systems Corp',
    invoiceDate: '2026-09-02',
    dueDate: '2026-09-17',
    amount: 356183,
    status: 'Posted',
    paymentTerms: 'Net 15 Days',
    lines: [
      {
        productName: 'Enterprise Fiber Switch 48-Port 10GbE',
        description: 'Rack level routing switches',
        quantity: 2,
        unitPrice: 115000,
        taxes: 38088,
        amount: 249688,
      },
      {
        productName: 'Custom On-Site Deployment & Migration Package',
        description: 'Installation & switch configuration',
        quantity: 1,
        unitPrice: 95000,
        taxes: 16245,
        amount: 106495,
      },
    ],
  },
  {
    id: 'inv-2',
    reference: 'INV/2026/00218',
    customerName: 'Stark Industries',
    invoiceDate: '2026-08-01',
    dueDate: '2026-08-31',
    amount: 345000,
    status: 'Paid',
    paymentTerms: 'Net 30 Days',
    lines: [
      {
        productName: 'DealFlow360 Enterprise ERP License (Monthly)',
        description: 'August 2026 Platform billing',
        quantity: 25,
        unitPrice: 12000,
        taxes: 45000,
        amount: 345000,
      },
    ],
  },
];

export const MOCK_DEAL_HEALTH_ALERTS: DealHealthItem[] = [
  {
    id: 'alert-1',
    quotationRef: 'SO/2026/00135',
    customerName: 'Tyrell BioTech Labs',
    repName: 'Peter Parker',
    amount: 890000,
    daysInactive: 14,
    riskCategory: 'Stalled Deal',
    severity: 'High',
    description: 'No customer activity or reply on negotiation portal for over 14 days after quote delivery.',
  },
  {
    id: 'alert-2',
    quotationRef: 'SO/2026/00142',
    customerName: 'Stark Industries',
    repName: 'Peter Parker',
    amount: 1332338,
    daysInactive: 2,
    riskCategory: 'Discount Anomaly',
    severity: 'Critical',
    description: 'Hardware line discount (18%) exceeds tier limit (15%). Margin compressed by 4.2%.',
  },
  {
    id: 'alert-3',
    quotationRef: 'SO/2026/00131',
    customerName: 'Massive Dynamic',
    repName: 'Bruce Vance',
    amount: 420000,
    daysInactive: 21,
    riskCategory: 'Delivery Slippage',
    severity: 'Medium',
    description: 'Warehouse split stock depletion delaying fulfillment delivery date by 5 business days.',
  },
];

export const MOCK_PORTAL_MESSAGES: PortalChatMessage[] = [
  {
    id: 'pm-1',
    sender: 'Sales Rep',
    senderName: 'Alex Rivera (DealFlow360)',
    timestamp: 'Yesterday at 15:30',
    text: 'Hello Stark Industries team! We have prepared your custom hardware and SLA quote with the enterprise tier terms.',
  },
  {
    id: 'pm-2',
    sender: 'Customer',
    senderName: 'Tony Stark (Procurement)',
    timestamp: 'Today at 09:15',
    text: 'Thanks Alex. Can we adjust the blade server line discount to 18% so we can authorize payment immediately today?',
  },
];

export const MOCK_PORTAL_QUOTE = {
  id: 'q-1',
  portal_token: 'active',
  reference: 'SO/2026/00142',
  customer_name: 'Stark Industries',
  customer_email: 'procurement@stark-industries.com',
  status: 'Pending Approval',
  date: '2026-09-04',
  expires_at: '2026-09-30',
  untaxed_amount: 1129100,
  tax_amount: 203238,
  total_amount: 1332338,
  lines: [
    {
      id: 1,
      product_name: 'Titan Blade Server Node X8',
      description: 'Primary datacenter expansion compute nodes (256GB RAM)',
      quantity: 4,
      unit_price: 245000,
      discount_pct: 18,
      subtotal: 803600,
    },
    {
      id: 2,
      product_name: '24/7 Dedicated SLA Infrastructure Support',
      description: 'Enterprise 1-year mission critical coverage',
      quantity: 1,
      unit_price: 45000,
      discount_pct: 10,
      subtotal: 40500,
    },
    {
      id: 3,
      product_name: 'DealFlow360 Enterprise ERP License (Monthly)',
      description: '25-seat monthly subscription plan',
      quantity: 25,
      unit_price: 12000,
      discount_pct: 5,
      subtotal: 285000,
    },
  ],
};
